### PR TITLE
Stackless issue #188: enable soft switching for sub-iterators, (async) generators and coroutines

### PR DESCRIPTION
**Pull request by akruis**
Enable soft switching for iterators/coroutines called by "yield from".
Work in progress, not functional, DO NOT MERGE!

### CODE REVIEW

**Comment by kristjanvalur** [comment]
The funny thing, is that "yield from" would be unnecessary if "stackless" soft-switching functionality (a c-stack less execution loop) had been widely embraced.  As it is, it is a hack to switch contexts, something that stackless does more effectively and intuitively.  And yet, we need to make stackless itself 'aware' of yield from .  Tsk, tsk.

**Comment by akruis** [comment]
Yes, it is really unfortunate, all the more since Stackless like soft switching can be implemented in every programming language.

**Comment by akruis** [comment]
It is ready now. This pull request enables stackless calls of sub-iterators and coroutines (technically: the YIELD_FROM opcode) and of the following methods, if soft-switching is enabled:
- generator.send() (generator.\_\_next__() was already stackless);
- coroutine.send();
- coroutine_wrapper.\_\_next__() and coroutine_wrapper.send();
- async_generator_asend.\_\_next__() and async_generator_asend.send().

With this change it is possible to soft switch into/from the compound
statements "async for" and "async with".

**Comment by akruis** [comment]
I didn't get any negative feedback yet. Therefore I'll commit the PR.

**Pull request merged**
